services:
  backend:
    build:
      context: ./backend
    container_name: carpay-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: carpay-frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    environment:
      - FLASK_ENV=development
    restart: always
    depends_on:
      - backend
